# Generated by Django 3.2 on 2021-05-03 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210503_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roles',
            name='user_roles',
            field=models.CharField(choices=[('User', 'User'), ('Agent', 'Agent'), ('Admin', 'Admin')], default='User', max_length=50),
        ),
    ]
