# Generated by Django 3.2 on 2021-05-21 06:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_widgetuseraccess_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='widgetuseraccess',
            name='allowed_host',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='widgetuseraccess',
            name='api_key',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
