# Generated by Django 3.2 on 2021-06-16 09:52

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Speakers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('speaker_name', models.CharField(max_length=50)),
                ('speaker_tts_code', models.CharField(help_text='This should be matched with tts speaker.', max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VaderSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('inactivity_time_out', models.PositiveIntegerField(default=0)),
                ('end_interaction', models.PositiveIntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GptCharacter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('gpt_key', models.PositiveIntegerField(choices=[(0, 'Alethea'), (1, 'Fine Art')], default=0)),
                ('prompt', models.TextField()),
                ('restricted_keywords', models.TextField()),
                ('constants', django.contrib.postgres.fields.jsonb.JSONField()),
                ('strip', models.BooleanField(default=False)),
                ('check_reponse', models.BooleanField(default=False)),
                ('strip_one', models.BooleanField(default=False, verbose_name='answer strip from one ')),
                ('temperature', models.FloatField()),
                ('max_tokens', models.IntegerField()),
                ('top_p', models.IntegerField()),
                ('presence_penalty', models.FloatField()),
                ('frequency_penalty', models.FloatField()),
                ('stop_username', models.CharField(blank=True, max_length=50, null=True)),
                ('character', models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, related_name='speaker', to='gpt3.speakers')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
