# Generated by Django 3.2 on 2021-06-16 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpt3', '0002_alter_gptcharacter_gpt_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='gptcharacter',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vadersetting',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
