# Generated by Django 3.2 on 2021-06-17 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gpt3', '0003_auto_20210616_1035'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gptcharacter',
            options={'verbose_name_plural': 'Gpt Character'},
        ),
        migrations.AlterModelOptions(
            name='speakers',
            options={'verbose_name_plural': 'Speakers'},
        ),
    ]
