# Generated by Django 3.2 on 2021-06-17 13:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gpt3', '0004_auto_20210617_1348'),
    ]

    operations = [
        migrations.CreateModel(
            name='GptSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('session', models.CharField(max_length=20)),
                ('gpt_character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gpt3.gptcharacter')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GptConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user_dialogue', models.TextField()),
                ('character_dialogue', models.TextField()),
                ('gpt_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gpt3.gptsession')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
