# Generated by Django 3.2 on 2021-05-04 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avatars', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avatar',
            old_name='created_at',
            new_name='created',
        ),
        migrations.AddField(
            model_name='avatar',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
