# Generated by Django 3.2 on 2021-05-05 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("avatars", "0002_auto_20210504_1933"),
    ]

    operations = [
        migrations.AddField(
            model_name="avatar",
            name="creator_link",
            field=models.CharField(default="", max_length=271),
            preserve_default=False,
        ),
    ]
