# Generated by Django 3.2 on 2021-05-05 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("avatars", "0003_avatar_creator_link"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="avatar",
            name="user",
        ),
    ]
