# Generated by Django 3.2 on 2021-05-07 10:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('avatars', '0006_alter_avatar_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avatar',
            name='user',
        ),
        migrations.AddField(
            model_name='avatar',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, blank=True, null=True,),
        ),
        migrations.DeleteModel(
            name='AvatarEmail',
        ),
    ]
