# Generated by Django 3.2 on 2021-06-16 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lipsync', '0002_auto_20210616_1035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='demo_base_url',
        ),
    ]
