# Generated by Django 3.2 on 2021-06-16 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gpt3', '0003_auto_20210616_1035'),
        ('lipsync', '0004_remove_charactersetting_gpt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charactersetting',
            name='character',
            field=models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, related_name='speaker_setting', to='gpt3.speakers'),
        ),
    ]
