# Generated by Django 3.2 on 2021-06-16 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lipsync', '0005_alter_charactersetting_character'),
    ]

    operations = [
        migrations.AddField(
            model_name='charactersetting',
            name='gpt',
            field=models.OneToOneField(default='973d9446-7eb6-4d91-b269-5dabe9675611', on_delete=django.db.models.deletion.CASCADE, related_name='character_setting', to='lipsync.character'),
            preserve_default=False,
        ),
    ]
