# Generated by Django 3.2 on 2021-06-17 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lipsync', '0006_charactersetting_gpt'),
    ]

    operations = [
        migrations.AddField(
            model_name='charactersetting',
            name='display_name_popup',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='charactersetting',
            name='show_character_speech_text',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='charactersetting',
            name='show_user_speech_text',
            field=models.BooleanField(default=True),
        ),
    ]
