# Generated by Django 3.2 on 2021-06-17 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lipsync', '0007_auto_20210617_0854'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='character',
            options={'verbose_name_plural': 'Characters'},
        ),
        migrations.AlterModelOptions(
            name='charactersetting',
            options={'verbose_name_plural': 'Character Setting'},
        ),
        migrations.AlterModelOptions(
            name='googletts',
            options={'verbose_name_plural': 'Google TTS'},
        ),
        migrations.AlterField(
            model_name='character',
            name='is_google_tts',
            field=models.BooleanField(default=False),
        ),
    ]
