# Generated by Django 3.2 on 2021-06-22 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lipsync', '0010_auto_20210617_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='character_name',
            field=models.CharField(max_length=50),
            preserve_default=False,
        ),
    ]
