# Generated by Django 3.2 on 2021-06-23 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lipsync', '0011_character_character_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwoDCharacter',
            fields=[
            ],
            options={
                'verbose_name': '2D Character',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('lipsync.character',),
        ),
        migrations.AddField(
            model_name='character',
            name='talking_video',
            field=models.FileField(blank=True, null=True, upload_to='talking_video/'),
        ),
        migrations.AddField(
            model_name='character',
            name='waiting_video',
            field=models.FileField(blank=True, null=True, upload_to='waiting_video/'),
        ),
        migrations.AlterField(
            model_name='character',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Audio'), (1, 'Video'), (2, '2D Character')], default=1),
        ),
    ]
